### ISSUE TITLE
Used your work, thanks

### ISSUE THREAD

**Issue by sauln** [marmakoide/miniball#1]
Hi @marmakoide,  

I just wanted to let you know that we adapted your miniball implementation to support [Cech complexes here](https://github.com/scikit-tda/cechmate/blob/master/cechmate/filtrations/cech.py).

Please let me know if this attribution is okay for you. We included the [license and your copyright](https://github.com/scikit-tda/cechmate/blob/master/cechmate/filtrations/miniball.py) in the adaptation.

**Comment by marmakoide** [comment]
Hi,

 Thanks for the notice ! You can use my code as you see fit

I noticed that you made a recursive implementation out of my iterative implementation, that I made from
the original recursive description... I did an iterative implementation to handle input of any size without reaching
the call stack limit. I'm not familiar with functools.lru_cache, but is it strictly equivalent to an iterative implementation ?

Cheers,
Alex

________________________________
De : Nathaniel Saul <notifications@github.com>
Envoyé : mardi 19 février 2019 20:27
À : marmakoide/miniball
Cc : Devert Alexandre; Mention
Objet : [marmakoide/miniball] Used your work, thanks (#1)


Hi @marmakoide<https://github.com/marmakoide>,

I just wanted to let you know that we adapted your miniball implementation to support Cech complexes here<https://github.com/scikit-tda/cechmate/blob/master/cechmate/filtrations/cech.py>.

Please let me know if this attribution is okay for you. We included the license and your copyright<https://github.com/scikit-tda/cechmate/blob/master/cechmate/filtrations/miniball.py> in the adaptation.

**Comment by sauln** [comment]
Great! Yes, the idea was that since we are only computing mini balls for simplicity complexes, when we compute higher order simplices, we will already have the information stored for the faces. Lru cache automates the caching of a function for hashable input.
