### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by kjgoodrick** [marmakoide/miniball#2]
Hello!

Just wanted to start by saying thanks for this package, it's been super easy to use and very helpful!

It seems like there is an issue with the way the setup is configured. If you try and install without numpy already installed I get this error:

````
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kyle\AppData\Local\Temp\pip-install-l8w5w9qt\miniball\setup.py", line 24, in <module>
        import miniball
      File "C:\Users\kyle\AppData\Local\Temp\pip-install-l8w5w9qt\miniball\miniball.py", line 22, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\kyle\AppData\Local\Temp\pip-install-l8w5w9qt\miniball\
````
It looks like it's coming from the import miniball command which tries to import numpy while pip is checking for dependencies. I think it's similar to this issue: https://stackoverflow.com/questions/11015692/pip-fails-to-install-packages-from-requirements-txt which was fixed in this commit https://github.com/pydata/numexpr/pull/133/commits/4cf0ef717bbef882458f37b4fc473f2ead140263 

Not too hard to work around for now, but it does break trying to install from a requirements file in a fresh virtual environment. 

Thanks!

-Kyle

**Comment by marmakoide** [comment]
I fixed setup.py, so that a fresh install in a virgin Python environment won't fail by trying to import numpy while the later is not installed yet.

I did it in the least sophisticated way possible, it should be rather robust. As a bonus, there's a tiny optimisation thrown away.

Thank you for the comprehensive error report, it was very helpful.

**Comment by kjgoodrick** [comment]
Thanks for the quick fix! I like it, nice and simple :)
