### ISSUE TITLE
get_bounding_ball() returns unreasonably large radius for simple test case

### ISSUE THREAD

**Issue by josephko91** [marmakoide/miniball#4]
Hi! I was testing miniball with some of my personal mesh files and I noticed that the estimated bounding sphere was much larger than the actual mesh. I condensed it down to a minimal reproducible example below. I'm not exactly sure what's going on because I didn't look under the hood of your program, but thought I should let you know. Please let me know if it's something I'm doing wrong on my end though! 
```
pts = np.asarray([[-6, -4, 5],
       [0, -2, 0],
       [-2, -6, -1]])

c, r = miniball.get_bounding_ball(pts)

print(c, r)
```

Output: 
[-3.10526316 -3.60526316  2.13157895] 16.76315789473684

plotting in 3-D you can clearly see that the bounding sphere calculated by get_bounding_ball() is way bigger than the minimal bounding sphere. 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/3221060/234087998-dcc773c7-ec19-4907-a087-9c6c5bc7e827.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/3221060/234088032-5aeb06dc-c914-485e-a719-ff56e4c6ac00.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/3221060/234088058-5c399577-c5e3-4aa5-9f31-16b68979f022.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/3221060/234088116-be37e9bb-0605-4c65-a686-acb8dbf71dc2.png">

**Comment by marmakoide** [comment]
The algorithm implemented by miniball rely on a routine that computes the circumsphere of N + 1 points, N being the number of dimensions of the points. Thus in 3d, with 3 points, the circumsphere routine fails. Good catch, I will implement the special case of the minimum bounding ball of N points or less ASAP.

**Comment by marmakoide** [comment]
Hi,
 After a good night of sleep, I figured out your problem : **miniball.get_bounding_ball** returns the squared radius of the bounding ball, not the radius of the bounding ball. Check it and you'll see the answer returned is correct.

**Comment by josephko91** [comment]
Ahhhh that makes sense. Thanks!

**Comment by josephko91** [comment]
hi @marmakoide 

Thanks for the response earlier. Unfortunately, I think I've run into some additional potential bugs. 

I tried a more complex example with mesh vertices and the resulting sphere does not encompass the points. 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/3221060/234630415-d8e7ff48-564d-4efe-8a7a-99d94bd756b2.png">

I used your suggestion to take radius as the square-root of the output from get_bounding_ball(). 

I've attached a text files with the points, and a minimal reproducible example for your examination. 

```
import miniball
import numpy as np
import matplotlib.pyplot as plt

# import points and get center and radius of bounding sphere
mesh_points = np.loadtxt('pts.txt', delimiter=',')
c, r2 = miniball.get_bounding_ball(subset_points)
r = np.sqrt(r2) # r2 = radius squared, r = radius

# prepare plot
fig = plt.figure()
ax = fig.add_subplot(projection='3d')

# plot points
ax.scatter(mesh_points[:,0], mesh_points[:,1], mesh_points[:,2])

# plot sphere
u, v = np.mgrid[0:2*np.pi:50j, 0:np.pi:50j]
x = r*np.cos(u)*np.sin(v)
y = r*np.sin(u)*np.sin(v)
z = r*np.cos(v)
ax.plot_surface(x-c[0], y-c[1], z-c[2], color='r', alpha=0.2)

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
plt.show()
```

Output: 
![image](https://user-images.githubusercontent.com/3221060/234631118-674e6242-fb81-40a9-be12-f540739b5755.png)


[pts.txt](https://github.com/marmakoide/miniball/files/11334805/pts.txt)

**Comment by marmakoide** [comment]
Your script have a typo. The sphere used for plotting is centered at the origin, and need to be translated to the center of the bounding ball. The following line

``ax.plot_surface(x-c[0], y-c[1], z-c[2], color='r', alpha=0.2)``

should be

``ax.plot_surface(x+c[0],y+c[1], z+c[2], color='r', alpha=0.2)``

and you will notice that the bounding ball is correct (it bounds all point) and likely minimal.

**Comment by josephko91** [comment]
Hi @marmakoide. Even after fixing the typo, the radius of the sphere is too small. Hmm...

This is the output with the correction. 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/3221060/234695546-3951284f-62d8-4a66-818b-9c38e9cde975.png">

Corrected script for the record:
```
import miniball
import numpy as np
import matplotlib.pyplot as plt

# import points and get center and radius of bounding sphere
mesh_points = np.loadtxt('pts.txt', delimiter=',')
c, r2 = miniball.get_bounding_ball(subset_points)
r = np.sqrt(r2) # r2 = radius squared, r = radius

# prepare plot
fig = plt.figure()
ax = fig.add_subplot(projection='3d')

# plot points
ax.scatter(mesh_points[:,0], mesh_points[:,1], mesh_points[:,2])

# plot sphere
u, v = np.mgrid[0:2*np.pi:50j, 0:np.pi:50j]
x = r*np.cos(u)*np.sin(v)
y = r*np.sin(u)*np.sin(v)
z = r*np.cos(v)
# ax.plot_surface(x-c[0], y-c[1], z-c[2], color='r', alpha=0.2)
ax.plot_surface(x+c[0], y+c[1], z+c[2], color='r', alpha=0.2)

ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
# plt.tight_layout()
ax.set_box_aspect(aspect=None, zoom=0.8)
# plt.figure(constrained_layout=True)
plt.show()
print(c, r)
```

**Comment by marmakoide** [comment]
I ran your exact script, with just this line changed (as it can't run otherwise)

``c, r2 = miniball.get_bounding_ball(subset_points)``

becoming

``c, r2 = miniball.get_bounding_ball(mesh_points)``

I get this plot
![Figure_1](https://user-images.githubusercontent.com/12803447/234699673-f8c94b9a-93dc-4782-b293-fb08a5dbf08c.png)

Furthermore, using the following line of code, I can confirm confidently that all points are within the bounding ball

``print(np.all(np.sum((mesh_points - c) ** 2, axis = 1) <= r2))``

**Comment by josephko91** [comment]
*doh* that was a silly mistake. 

The 'subset_points' was an artifact of some quick testing. And I forgot to replace 'mesh_points' back in. That fixed the issue! Thanks so much for your help.
