### ISSUE TITLE
LinAlgError: Singular matrix

### ISSUE THREAD

**Issue by LeviZhang1996** [marmakoide/miniball#5]
hello,I am a student who using your module  intend to calculate the miniball enclosing a list of 3d points.Unfortunately.Sometimes,I met an error like this:
![image](https://github.com/marmakoide/miniball/assets/83460341/5357839f-f44e-4cf2-bf33-b89fca8cdec0)
 Ithink it maybe relevant with the pseudo-random number generation?I don't know how to fix it,could you help me?
the input point list is in below text.
[bifurcates_group_position.txt](https://github.com/marmakoide/miniball/files/11957672/bifurcates_group_position.txt)

**Comment by marmakoide** [comment]
Hi,
 Your dataset have identical points, which is the source of your problem. This is explained in the documentation aka the front page of the github repository : miniball assumes there are no duplicates for performance reason. You can remove duplicates using the numpy.unique function. This solves your issue with your problem, I checked it.

**Comment by marmakoide** [comment]
Hi,
 Your dataset have identical points, which is the source of your problem. This is explained in the documentation aka the front page of the github repository : miniball assumes there are no duplicates for performance reason. You can remove duplicates using the numpy.unique function. This solves your issue with your problem, I checked it.
